### ISSUE TITLE
Proxy option

### ISSUE THREAD

**Issue by bucinskasj** [francescov1/facebook-event-scraper#1]
Since you are using Axios to make requests, i'm wondering if it would be possible to pass in Proxy URL and auth parameters into the request to make this a bit more "secure".

**Comment by francescov1** [comment]
Great idea, Ill create a PR shortly

**Comment by francescov1** [comment]
@bucinskasj Hows this? https://github.com/francescov1/facebook-event-scraper/pull/2/files

**Comment by bucinskasj** [comment]
@francescov1 it's great! Exactly what i was looking for!

**Comment by francescov1** [comment]
@bucinskasj Live in v0.04!

**Comment by bucinskasj** [comment]
Great stuff @francescov1 ! Thank you!
