### ISSUE TITLE
Timestamp is truncated?

### ISSUE THREAD

**Issue by velsa** [francescov1/facebook-event-scraper#18]
It looks like `startTimestamp` and `endTimestamp` are too short. 

How do I get the real date and time using those values?

E.g. when I get 

```
startTimestamp: 1708776000,
endTimestamp: 1708780800,
formattedDate: 'Saturday, February 24, 2024 at 2:00 PM – 3:20 PM IST',
timezone: 'UTC+02',
```

If I do 

```
console.log(new Date(1708776000).toISOString())
console.log(new Date(1708780800).toISOString())
```

The result is

```
1970-01-20T18:39:36.000Z
1970-01-20T18:39:40.800Z
```

**Comment by velsa** [comment]
Ok, I just realized that I simply need to multiply the timestamp by 1000.

Which is a bit weird, but it works :)

**Comment by francescov1** [comment]
Yes you got it. JavaScript uses milliseconds for time stamps, whereas most other sources use seconds. So multiplying by 1000 fixes it. 

The data being returned by this library is unaltered, I wanted to avoid doing any sort of manipulation so that the data is consistent with Fb
