### ISSUE TITLE
Support multiple dates in FB event

### ISSUE THREAD

**Issue by velsa** [francescov1/facebook-event-scraper#20]
First of let me thank you for your work on this project! 
It really helps me get all the events from my FB into a database.

I noticed one thing that is not supported in your scraper – events with multiple dates in them. E.g. https://www.facebook.com/events/461258746357325/461258759690657

Is there a way to get this information from the event page?

Thanks!

**Comment by francescov1** [comment]
Hey @velsa, will take a look this weekend! Thanks for flagging this

**Comment by velsa** [comment]
Hey @francescov1

Thanks for taking note of this issue!

Any progress on it?

**Comment by francescov1** [comment]
Hey @velsa, sorry for the delay, got busy at work. I took a quick look and it looks like the data is available, I'll try to get support done today or early next week. Will keep you posted!

**Comment by francescov1** [comment]
@velsa This is now supported in v0.1.2 🚀 See [readme](https://github.com/francescov1/facebook-event-scraper?tab=readme-ov-file#multi-date-events) for more info (`siblingEvents` and `parentEvent` fields).
