### ISSUE TITLE
Some events are not scraped even though they are public

### ISSUE THREAD

**Issue by bucinskasj** [francescov1/facebook-event-scraper#3]
Not sure what is the issue here. Some events are not scraped, even though they are public

- Tried both with proxy and without proxy
- At least for now, they are coming from a single event promoter. Might not be related(promoter in question https://www.facebook.com/bilietai.lt/ )
- What is strange that some events from that promoter work and some don't

## Examples
- https://www.facebook.com/events/1305645013617173/
- https://www.facebook.com/events/1430440007735081/

**Comment by francescov1** [comment]
@bucinskasj will investigate in the next couple days, thanks for submitting

**Comment by francescov1** [comment]
@bucinskasj Took a quick look actually, turns out we werent properly handling the case where event hosts hide the guest list. Releasing a fix shortly [here](https://github.com/francescov1/facebook-event-scraper/pull/4/files)

**Comment by francescov1** [comment]
Fix is live in v0.0.5!

**Comment by bucinskasj** [comment]
Works like a charm! Thank you, Francesco!
