### ISSUE TITLE
"Cannot read properties of undefined (reading 'photo')"

### ISSUE THREAD

**Issue by bucinskasj** [francescov1/facebook-event-scraper#5]
Thanks for a great package. We've been using it extensively for the past week!

It appears that in some cases the scraper returns 500 error, because the event photo is not defined. It seems it's because the event image is replaced by videos in some of the events:

Here's an example: https://www.facebook.com/events/242861135088721/

**Comment by francescov1** [comment]
Oh good catch, I hadn't come across any events like this before! Should be an easy fix

**Comment by francescov1** [comment]
Hows this look? https://github.com/francescov1/facebook-event-scraper/pull/6

**Comment by bucinskasj** [comment]
Looks great!

**Comment by francescov1** [comment]
Fix is live in v0.06 🚀
