### ISSUE TITLE
Error: Invalid start character: n

### ISSUE THREAD

**Issue by bucinskasj** [francescov1/facebook-event-scraper#7]
Hey,

This is something that we are seeing quite often in our logs. Some public Facebook event links return this error:

`Error: Invalid start character: n
 at findJsonInString (/var/app/current/node_modules/facebook-event-scraper/dist/utils/json.js:27:19)
at Object.getLocation (/var/app/current/node_modules/facebook-event-scraper/dist/utils/htmlParser.js:62:54)
at /var/app/current/node_modules/facebook-event-scraper/dist/scraper.js:49:31
at Generator.next (<anonymous>)
at fulfilled (/var/app/current/node_modules/facebook-event-scraper/dist/scraper.js:28:58)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)`

It seems to happen when:
- Where's no location data at all
- Location data only includes a really basic info like City
- Location only includes GPS coordinates + Facebook page location

Here are some examples:

No location data:
- https://www.facebook.com/events/782998640138266/
- https://www.facebook.com/events/1275452883399884/
- https://www.facebook.com/events/911737676493937/911741153160256/
- https://www.facebook.com/events/979092850106402/

Basic location data
- https://www.facebook.com/events/170411189327647/

GPS coordinates only
- https://www.facebook.com/events/221439007315129/
- https://www.facebook.com/events/653729686596474/

**Comment by francescov1** [comment]
Thanks for submitting, must be some other edge cases I missed. I'll get on it right away!

**Comment by francescov1** [comment]
Hey @bucinskasj,

This PR fixes the bug for no location data https://github.com/francescov1/facebook-event-scraper/pull/8.

For the other two cases you provided (basic location data & GPS coordinates), I can't actually see any any location info associated with those events, are you sure they have this basic location data set? With the new changes from the PR above, they would also return a location of `null` but I want to ensure I didn't miss anything for them

**Comment by bucinskasj** [comment]
Tested the fix.

It works perfectly for events that don't have any location data and fixed the other issues too, where on the Facebook UI it only showed the city, on the right hand side map.

The only strange thing is here:

These 2 events happen at the same location. 
#1  https://www.facebook.com/events/221439007315129/
#2 https://www.facebook.com/events/653729686596474/

None of them could be scraped before, however:

#2 works as expected, however #1 throws an error. Looking at the Facebook UI, i see that #1 only has the GPS coordinates on the right hand side map, while #2 managed to pick up additional location details and shows that on the map.

#2 correctly does not return the location data, because it's useless and not full
#1 on the other hand throws "Something went wrong. Check link" error

**Comment by francescov1** [comment]
Got it, will investigate. At first glance, it seems that No1 requires users to login to view the event, so I suspect thats why it throws an error. Will get back to you shortly

**Comment by francescov1** [comment]
Hey @bucinskasj,

The issues you mentioned become clear if you try to view the two events without being authenticated. For No1, Facebook requires a login to view the event. For No2, there is no map/GPS data available until you login, so thats why we arent getting the location data. I made a small change to make the error message reflect this better: https://github.com/francescov1/facebook-event-scraper/pull/9

Currently this tool does not support authentication for FB, but if its a common use case we could start looking into it.

Feel free to re-open this issue if there's anything else!

**Comment by bucinskasj** [comment]
Thank you @francescov1 !
